apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aprocd-project
spec:
  destination:
    namespace: argocd-app
    server: https://kubernetes.default.svc
  source:
    path: ./manifest
    repoURL: https://github.com/danushvithiyarth/GitOps-Manifest-Repo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
